let state, selection, historyRevisionId; const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const res=await fetch(path,{headers:{"content-type":"application/json"},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||"Request failed");return data}
async function load(message){state=await api("/api/state");render();if(message)notice(message)}
function inline(s){return esc(s).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\*([^*]+)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>')}
function markdownLine(line,inCode){if(/^```/.test(line))return {html:"",code:!inCode};if(inCode)return{html:esc(line),cls:"block-code",code:inCode};let m;if(m=line.match(/^(#{1,3})\s+(.*)$/))return{html:`<h${m[1].length}>${inline(m[2])}</h${m[1].length}>`,code:inCode};if(m=line.match(/^>\s?(.*)$/))return{html:inline(m[1]),cls:"quote",code:inCode};if(m=line.match(/^[-*+]\s+(.*)$/))return{html:"• "+inline(m[1]),cls:"list",code:inCode};if(m=line.match(/^\d+\.\s+(.*)$/))return{html:inline(line),cls:"list",code:inCode};return{html:inline(line),code:inCode}}
function render(){document.title=`${state.document.name} — jstack-md`;$("#filename").textContent=state.document.name;let code=false,html="";const threads=new Map();for(const t of state.threads){const key=t.orphaned?0:t.anchor.endLine;(threads.get(key)||threads.set(key,[]).get(key)).push(t)}state.document.content.split("\n").forEach((line,i)=>{const out=markdownLine(line,code);code=out.code;html+=`<div class="doc-line" data-line="${i+1}"><span class="line-no">${i+1}</span><div class="line-body ${out.cls||""}">${out.html||"&nbsp;"}</div></div>`;for(const t of threads.get(i+1)||[])html+=threadHtml(t)});for(const t of threads.get(0)||[])html+=threadHtml(t);$("#document").innerHTML=html;renderHistory();$("#binding").textContent=state.agentBinding?`Bound to ${state.agentBinding.provider}${state.agentBinding.sessionId?` · ${state.agentBinding.sessionId}`:""}`:"No authoring agent is bound."}
function threadHtml(t){const waiting=t.status==="open"&&t.messages.at(-1)?.author==="human";return `<article class="thread ${t.status} ${t.orphaned?"orphaned":""}" data-thread="${t.id}"><div class="thread-head"><span>${t.orphaned?"Detached · ":""}${t.status==="resolved"?"Resolved":"Open thread"} · lines ${t.anchor.startLine}–${t.anchor.endLine}</span><button data-status="${t.status==="open"?"resolved":"open"}">${t.status==="open"?"Resolve":"Reopen"}</button></div>${t.messages.map(m=>`<div class="message ${m.author}"><span class="author">${esc(m.author)}</span><p>${esc(m.content)}</p></div>`).join("")}${waiting?'<div class="agent-waiting">••• Agent notified</div>':""}<form class="reply"><input placeholder="Continue this conversation…" aria-label="Reply"><button>Reply</button></form></article>`}
function renderHistory(){const selected=historyRevisionId||state.revision.id;$("#revisionList").innerHTML=[...state.revisions].reverse().map(r=>`<button class="revision-choice ${r.id===selected?"selected":""}" data-revision="${r.id}"><strong>Revision ${r.number}</strong><span>${esc(r.reason||"Document changed")}</span><span>${new Date(r.createdAt).toLocaleString()}</span></button>`).join("")}
async function selectHistoryRevision(id){historyRevisionId=id;renderHistory();const revision=state.revisions.find(r=>r.id===id),data=await api(`/api/revisions/${id}/diff`);$("#historyRevision").textContent=`Revision ${revision.number}`;$("#historyMeta").textContent=`${revision.reason||"Document changed"} · ${new Date(revision.createdAt).toLocaleString()}`;$("#restoreRevision").dataset.restore=id;$("#restoreRevision").disabled=id===state.revision.id;$("#historyDiff").innerHTML=data.diff.split("\n").map(line=>`<span class="${line.startsWith("+")?"add":line.startsWith("-")?"del":""}">${esc(line)}</span>`).join("\n")}
document.addEventListener("mouseup",e=>{if(e.target.closest(".thread,#composer,header,dialog"))return;const sel=getSelection();if(!sel||sel.isCollapsed)return;const text=sel.toString().trim();const start=elLine(sel.anchorNode),end=elLine(sel.focusNode);if(!text||!start||!end)return;const a=Math.min(start,end),b=Math.max(start,end),lines=state.document.content.split("\n");selection={startLine:a,endLine:b,selectedText:text,prefix:lines.slice(Math.max(0,a-3),a-1).join("\n"),suffix:lines.slice(b,b+2).join("\n")};const box=sel.getRangeAt(0).getBoundingClientRect(),c=$("#composer");c.hidden=false;c.style.left=Math.min(innerWidth-390,Math.max(10,box.left))+'px';c.style.top=Math.min(innerHeight-190,box.bottom+10)+'px';c.querySelector(".selection").textContent=`“${text}” · lines ${a}–${b}`;c.querySelector("textarea").focus()});
function elLine(node){return node?.nodeType===3?node.parentElement?.closest(".doc-line")?.dataset.line:node?.closest?.(".doc-line")?.dataset.line}
$("#composer [data-cancel]").onclick=()=>$("#composer").hidden=true;$("#composer [data-submit]").onclick=async()=>{const textarea=$("#composer textarea"),comment=textarea.value.trim();if(!comment)return;await api("/api/threads",{method:"POST",body:JSON.stringify({anchor:selection,comment})});textarea.value="";$("#composer").hidden=true;getSelection().removeAllRanges();await load("Comment sent to the authoring agent.")};
$("#document").addEventListener("click",async e=>{if(e.target.matches(".line-no")){const line=Number(e.target.closest(".doc-line").dataset.line),lines=state.document.content.split("\n"),text=lines[line-1];if(!text.trim())return;selection={startLine:line,endLine:line,selectedText:text,prefix:lines.slice(Math.max(0,line-3),line-1).join("\n"),suffix:lines.slice(line,line+2).join("\n")};const box=e.target.getBoundingClientRect(),c=$("#composer");c.hidden=false;c.style.left=Math.min(innerWidth-390,Math.max(10,box.right+8))+'px';c.style.top=Math.min(innerHeight-190,box.bottom+8)+'px';c.querySelector(".selection").textContent=`“${text}” · line ${line}`;c.querySelector("textarea").focus();return}const status=e.target.dataset.status;if(status){await api(`/api/threads/${e.target.closest(".thread").dataset.thread}/status`,{method:"POST",body:JSON.stringify({status})});await load()} });
$("#document").addEventListener("submit",async e=>{if(!e.target.matches(".reply"))return;e.preventDefault();const input=e.target.querySelector("input"),content=input.value.trim();if(!content)return;await api(`/api/threads/${e.target.closest(".thread").dataset.thread}/messages`,{method:"POST",body:JSON.stringify({author:"human",content})});input.value="";await load()});
$("#history").onclick=async()=>{historyRevisionId=state.revision.id;$("#historyDialog").showModal();await selectHistoryRevision(historyRevisionId)};$("[data-history-close]").onclick=()=>$("#historyDialog").close();$("#revisionList").onclick=e=>{const button=e.target.closest("[data-revision]");if(button)selectHistoryRevision(button.dataset.revision)};$("#restoreRevision").onclick=async e=>{const id=e.currentTarget.dataset.restore;if(!id||!confirm("Restore this revision as a new revision?"))return;await api(`/api/revisions/${id}/restore`,{method:"POST",body:"{}"});$("#historyDialog").close();historyRevisionId=null;await load("Revision restored and saved as a new revision.")};
$("#finish").onclick=()=>{const n=state.threads.filter(t=>t.status==="open").length;$("#finishText").textContent=n?`${n} open thread${n===1?"":"s"} remain. The result will be completed-with-open-threads.`:"All threads are resolved. The result will be approved.";$("#finishDialog").showModal()};$("#finishDialog [data-cancel]").onclick=()=>$("#finishDialog").close();$("#finishDialog [data-finish]").onclick=()=>finish("finish");$("#finishDialog [data-abandon]").onclick=()=>finish("abandoned");async function finish(result){const out=await api("/api/finish",{method:"POST",body:JSON.stringify({result})});$("#finishDialog").close();document.body.innerHTML=`<div class="done"><h1>Review ${esc(out.result)}</h1><p>You can close this window and return to the authoring agent.</p></div>`}
function notice(s){$("#notice").textContent=s;setTimeout(()=>$("#notice").textContent="",3500)}
const events=new EventSource("/events");events.addEventListener("revision",()=>load("The document changed. A new revision was created."));events.addEventListener("message",()=>load());events.addEventListener("thread",()=>load());
await load();
